apiVersion: v1
kind: Service
metadata:
  name: home-mqtt
spec:
  type: NodePort
  selector:
    app: home-mqtt
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
      nodePort: 31883

