apiVersion: v1
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data
    listener 1883 0.0.0.0
    allow_anonymous true
kind: ConfigMap
metadata:
  name: home-mqtt


