apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-mqtt
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /volume1/public/k8s/data/home-mqtt
    server: synology

